package Hibernate.POJOs;
// Generated 14-ene-2016 18:37:10 by Hibernate Tools 4.3.1



/**
 * Basket generated by hbm2java
 */
public class Basket  implements java.io.Serializable {


     private Integer cod;
     private Product product;
     private User user;
     private int amount;

    public Basket() {
    }

    public Basket(Product product, User user, int amount) {
       this.product = product;
       this.user = user;
       this.amount = amount;
    }
   
    public Integer getCod() {
        return this.cod;
    }
    
    public void setCod(Integer cod) {
        this.cod = cod;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }




}


