package Hibernate.POJOs;
// Generated 09-ene-2016 21:01:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material  implements java.io.Serializable {


     private Integer cod;
     private String name;
     private Set productMaterials = new HashSet(0);

    public Material() {
    }

	
    public Material(String name) {
        this.name = name;
    }
    public Material(String name, Set productMaterials) {
       this.name = name;
       this.productMaterials = productMaterials;
    }
   
    public Integer getCod() {
        return this.cod;
    }
    
    public void setCod(Integer cod) {
        this.cod = cod;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProductMaterials() {
        return this.productMaterials;
    }
    
    public void setProductMaterials(Set productMaterials) {
        this.productMaterials = productMaterials;
    }




}


