package Hibernate.POJOs;
// Generated 14-ene-2016 18:37:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductRecord generated by hbm2java
 */
public class ProductRecord  implements java.io.Serializable {


     private Integer cod;
     private Product product;
     private Record record;
     private int amount;
     private Set turnovers = new HashSet(0);

    public ProductRecord() {
    }

	
    public ProductRecord(Product product, Record record, int amount) {
        this.product = product;
        this.record = record;
        this.amount = amount;
    }
    public ProductRecord(Product product, Record record, int amount, Set turnovers) {
       this.product = product;
       this.record = record;
       this.amount = amount;
       this.turnovers = turnovers;
    }
   
    public Integer getCod() {
        return this.cod;
    }
    
    public void setCod(Integer cod) {
        this.cod = cod;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Record getRecord() {
        return this.record;
    }
    
    public void setRecord(Record record) {
        this.record = record;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public Set getTurnovers() {
        return this.turnovers;
    }
    
    public void setTurnovers(Set turnovers) {
        this.turnovers = turnovers;
    }




}


