package Hibernate.POJOs;
// Generated 09-ene-2016 21:01:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer cod;
     private Category category;
     private String name;
     private double price;
     private Set baskets = new HashSet(0);
     private Set productRecords = new HashSet(0);
     private Set productMaterials = new HashSet(0);

    public Product() {
    }

	
    public Product(Category category, String name, double price) {
        this.category = category;
        this.name = name;
        this.price = price;
    }
    public Product(Category category, String name, double price, Set baskets, Set productRecords, Set productMaterials) {
       this.category = category;
       this.name = name;
       this.price = price;
       this.baskets = baskets;
       this.productRecords = productRecords;
       this.productMaterials = productMaterials;
    }
   
    public Integer getCod() {
        return this.cod;
    }
    
    public void setCod(Integer cod) {
        this.cod = cod;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public Set getBaskets() {
        return this.baskets;
    }
    
    public void setBaskets(Set baskets) {
        this.baskets = baskets;
    }
    public Set getProductRecords() {
        return this.productRecords;
    }
    
    public void setProductRecords(Set productRecords) {
        this.productRecords = productRecords;
    }
    public Set getProductMaterials() {
        return this.productMaterials;
    }
    
    public void setProductMaterials(Set productMaterials) {
        this.productMaterials = productMaterials;
    }




}


