package Hibernate.POJOs;
// Generated 14-ene-2016 18:37:10 by Hibernate Tools 4.3.1



/**
 * RecordUser generated by hbm2java
 */
public class RecordUser  implements java.io.Serializable {


     private Integer cod;
     private Record record;
     private User user;

    public RecordUser() {
    }

    public RecordUser(Record record, User user) {
       this.record = record;
       this.user = user;
    }
   
    public Integer getCod() {
        return this.cod;
    }
    
    public void setCod(Integer cod) {
        this.cod = cod;
    }
    public Record getRecord() {
        return this.record;
    }
    
    public void setRecord(Record record) {
        this.record = record;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


