package Hibernate.POJOs;
// Generated 14-ene-2016 18:37:10 by Hibernate Tools 4.3.1



/**
 * Turnover generated by hbm2java
 */
public class Turnover  implements java.io.Serializable {


     private Integer cod;
     private ProductRecord productRecord;
     private int amount;
     private double price;

    public Turnover() {
    }

    public Turnover(ProductRecord productRecord, int amount, double price) {
       this.productRecord = productRecord;
       this.amount = amount;
       this.price = price;
    }
   
    public Integer getCod() {
        return this.cod;
    }
    
    public void setCod(Integer cod) {
        this.cod = cod;
    }
    public ProductRecord getProductRecord() {
        return this.productRecord;
    }
    
    public void setProductRecord(ProductRecord productRecord) {
        this.productRecord = productRecord;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


